services:
    app:
        build:
            context: ./app
        container_name: app
        working_dir: /var/www
        volumes:
            - ${APP_CODE_PATH_HOST}:/var/www:cached
        networks:
            - app-network

    web:
        image: nginx:alpine
        container_name: web
        ports:
            - "80:80"
        volumes:
            - ${APP_CODE_PATH_HOST}:/var/www:cached
            - ./nginx/sites/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app-network

    php-worker:
        build:
            context: ./app
        container_name: php-worker
        working_dir: /var/www
        volumes:
            - ${APP_CODE_PATH_HOST}:/var/www:cached
            - ./php-worker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        command: supervisord -c /etc/supervisor/conf.d/supervisord.conf
        depends_on:
            - app
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
