services:
    app:
        build:
            context: ./app
        container_name: app
        working_dir: /var/www
        volumes:
            - ../nux-games.com:/var/www
        networks:
            - app-network

    web:
        image: nginx:alpine
        container_name: web
        volumes:
            - ../nux-games.com:/var/www
            - ./nginx/sites/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        networks:
            - app-network

    php-worker:
        image: php:8.0-fpm
        container_name: php-worker
        working_dir: /var/www
        volumes:
            - ../nux-games.com:/var/www
            - ./php-worker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        command: supervisord -c /etc/supervisor/conf.d/supervisord.conf
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
